### ISSUE TITLE
Error - 'DataFrame' object has no attribute 'sort_values'

### ISSUE THREAD

**Issue by zakipatel** [julioasotodv/spark-df-profiling#5]
Running on Spark 2.0: 

When i run the following command on a data frame with one integer column, I get a a result. 

report = spark_df_profiling.ProfileReport(df)

However, if there are additional (non-integer) columns in the data frame, i get the error : - 'DataFrame' object has no attribute 'sort_values'

**Comment by julioasotodv** [comment]
Hi again!

Just like with six, make sure you are running at least pandas 0.17. Take a try and let me know if it works!
